---
version: "2.1"
services:
  webtop:
    image: lscr.io/linuxserver/webtop:amd64-ubuntu-kde
    container_name: webtop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      #- SUBFOLDER=/ #optional
      - KEYBOARD=en-us-qwerty #optional
    volumes:
      - ./config:/config
    ports:
      - 3000:3000
    shm_size: "4gb" #optional
    restart: unless-stopp
